# Generated by Django 5.2.3 on 2025-06-26 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgnc_id', models.CharField(default=None, max_length=40, null=True, unique=True)),
                ('hgnc_symbol', models.CharField(default=None, max_length=50, null=True, unique=True)),
                ('hgnc_name', models.CharField(default=None, max_length=250, null=True)),
                ('hmdb_accession', models.CharField(default=None, max_length=100, null=True, unique=True)),
                ('hmdb_name', models.CharField(default=None, max_length=400, null=True, unique=True)),
                ('type', models.CharField(choices=[('G', 'Gene'), ('M', 'Metabolite')], default='G', max_length=1)),
                ('datetime_updated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('doi', models.CharField(max_length=100, unique=True, verbose_name='DOI URL')),
                ('publisher_url', models.CharField(blank=True, max_length=300, null=True, verbose_name="Publisher's URL")),
                ('s4me_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='S4ME URL')),
                ('preprint', models.BooleanField(default=False, verbose_name='Preprint')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control', models.ManyToManyField(related_name='control_study_cohorts', to='sickgenes.disease')),
                ('disease', models.ManyToManyField(related_name='disease_study_cohorts', to='sickgenes.disease')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.study')),
            ],
        ),
        migrations.CreateModel(
            name='MoleculeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.molecule')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol'], name='molecule_alias_symbol_idx')],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sickgenes.molecule')),
                ('study_cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.studycohort')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('study_cohort', 'molecule'), name='unique_study_gene')],
            },
        ),
    ]
