# Generated by Django 5.2.3 on 2025-06-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moleculealias',
            name='molecule_alias_symbol_idx',
        ),
        migrations.RenameField(
            model_name='moleculealias',
            old_name='symbol',
            new_name='alias',
        ),
        migrations.AddIndex(
            model_name='moleculealias',
            index=models.Index(fields=['alias'], name='molecule_alias_symbol_idx'),
        ),
    ]
