# Generated by Django 5.2.3 on 2025-06-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0002_remove_moleculealias_molecule_alias_symbol_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='molecule',
            options={'verbose_name': 'molecule', 'verbose_name_plural': 'molecules'},
        ),
        migrations.AlterModelOptions(
            name='moleculealias',
            options={'verbose_name': 'molecule alias', 'verbose_name_plural': 'molecule aliases'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name_plural': 'studies'},
        ),
        migrations.AddConstraint(
            model_name='moleculealias',
            constraint=models.UniqueConstraint(fields=('molecule', 'alias'), name='unique_molecule_alias'),
        ),
    ]
