# Generated by Django 5.2.3 on 2025-06-29 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0003_alter_molecule_options_alter_moleculealias_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moleculealias',
            name='molecule_alias_symbol_idx',
        ),
    ]
