# Generated by Django 5.2.3 on 2025-06-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0004_remove_moleculealias_molecule_alias_symbol_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='molecule',
            index=models.Index(fields=['type'], name='molecule_type'),
        ),
    ]
