# Generated by Django 5.2.3 on 2025-06-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0005_molecule_molecule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='type',
            field=models.CharField(choices=[('G', 'Gene'), ('M', 'Metabolite')], max_length=1),
        ),
    ]
