# Generated by Django 5.2.3 on 2025-06-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0006_alter_molecule_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='molecule',
            options={'ordering': ['hgnc_symbol', 'hmdb_name'], 'verbose_name': 'molecule', 'verbose_name_plural': 'molecules'},
        ),
        migrations.AlterModelOptions(
            name='moleculealias',
            options={'ordering': ['alias'], 'verbose_name': 'molecule alias', 'verbose_name_plural': 'molecule aliases'},
        ),
        migrations.AddIndex(
            model_name='molecule',
            index=models.Index(fields=['hgnc_name'], name='hgnc_name_index'),
        ),
    ]
