# Generated by Django 5.2.3 on 2025-06-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0007_alter_molecule_options_alter_moleculealias_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moleculealias',
            index=models.Index(fields=['alias'], name='moleculealias_alias_idx'),
        ),
    ]
