# Generated by Django 5.2.3 on 2025-06-30 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0008_moleculealias_moleculealias_alias_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='HgncGene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgnc_id', models.CharField(default=None, max_length=40, null=True, unique=True)),
                ('symbol', models.CharField(default=None, max_length=50, null=True)),
                ('name', models.CharField(default=None, max_length=250, null=True)),
                ('datetime_updated', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='hgncgene_symbol_idx'), models.Index(fields=['name'], name='hgncgene_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='HgncGeneExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('field_name', models.CharField(choices=[('ENT', 'Entrez gene ID'), ('ENS', 'Ensembl gene ID'), ('VEG', 'Vega gene ID'), ('UCS', 'UCSC gene ID'), ('ENA', 'International Nucleotide Sequence Database Collaboration accession number'), ('UNI', 'UniProt Protein Accession'), ('PUB', 'Pubmed PMID'), ('OMI', 'Online Mendelian Inheritance in Man (OMIM) ID'), ('ALS', 'Alias symbol'), ('ALN', 'Alias name'), ('PRA', 'Previous symbol'), ('PRN', 'Previous name')], default=None, max_length=3, null=True)),
                ('hgnc_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene')),
            ],
            options={
                'ordering': ['field_name', 'value'],
                'indexes': [models.Index(fields=['value'], name='hgncgeneextra_value_idx'), models.Index(fields=['field_name'], name='hgncgeneextra_fieldname_idx')],
            },
        ),
    ]
