# Generated by Django 5.2.3 on 2025-07-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0009_hgncgene_hgncgeneextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='HmdbMetabolite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
