# Generated by Django 5.2.3 on 2025-07-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0010_hmdbmetabolite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HgncGeneExtra',
        ),
    ]
