# Generated by Django 5.2.3 on 2025-07-01 16:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0011_delete_hgncgeneextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgncgene',
            name='alias_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=200, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='alias_symbol',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=40, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='emsembl_gene_id',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='ena',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=15, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='entrez_id',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='omim_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=None, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='prev_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=200, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='prev_symbol',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=25, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='pubmed_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(default=None, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='ucsc_id',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='uniprot_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=None, max_length=15, null=True), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='vega_id',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='hgnc_id',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='symbol',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(fields=['entrez_id'], name='hgncgene_entrez_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(fields=['emsembl_gene_id'], name='hgncgene_emsembl_gene_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(fields=['vega_id'], name='hgncgene_vega_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(fields=['ucsc_id'], name='hgncgene_ucsc_id_idx'),
        ),
    ]
