# Generated by Django 5.2.3 on 2025-07-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0012_hgncgene_alias_name_hgncgene_alias_symbol_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hgncgene',
            name='hgncgene_emsembl_gene_id_idx',
        ),
        migrations.RenameField(
            model_name='hgncgene',
            old_name='emsembl_gene_id',
            new_name='ensembl_gene_id',
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(fields=['ensembl_gene_id'], name='hgncgene_ensembl_gene_id_idx'),
        ),
    ]
