# Generated by Django 5.2.3 on 2025-07-01 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0013_remove_hgncgene_hgncgene_emsembl_gene_id_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='molecule',
        ),
        migrations.AddField(
            model_name='finding',
            name='hgnc_gene',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sickgenes.hgncgene'),
        ),
        migrations.DeleteModel(
            name='MoleculeAlias',
        ),
        migrations.DeleteModel(
            name='Molecule',
        ),
    ]
