# Generated by Django 5.2.3 on 2025-07-02 02:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0014_remove_finding_molecule_finding_hgnc_gene_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hgncgene',
            name='alias_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='alias_symbol',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='ena',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='omim_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='prev_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='prev_symbol',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='pubmed_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='uniprot_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=None),
        ),
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('study_cohort', 'hgnc_gene'), name='unique_study_gene'),
        ),
    ]
