# Generated by Django 5.2.3 on 2025-07-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0015_remove_finding_unique_study_gene_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='finding',
            name='unique_study_gene',
        ),
        migrations.RemoveField(
            model_name='hgncgene',
            name='pubmed_id',
        ),
    ]
