# Generated by Django 5.2.3 on 2025-07-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0016_remove_finding_unique_study_gene_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='finding',
            constraint=models.UniqueConstraint(fields=('study_cohort', 'hgnc_gene'), name='unique_study_gene'),
        ),
    ]
