# Generated by Django 5.2.3 on 2025-07-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0017_finding_unique_study_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycohort',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_cohorts', to='sickgenes.study'),
        ),
    ]
