# Generated by Django 5.2.3 on 2025-07-04 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0018_alter_studycohort_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studycohort',
            old_name='control',
            new_name='control_tags',
        ),
        migrations.RenameField(
            model_name='studycohort',
            old_name='disease',
            new_name='disease_tags',
        ),
    ]
