# Generated by Django 5.2.3 on 2025-07-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0019_rename_control_studycohort_control_tags_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finding',
            new_name='GeneFinding',
        ),
    ]
