# Generated by Django 5.2.3 on 2025-07-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0020_rename_finding_genefinding'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genefinding',
            name='unique_study_gene',
        ),
        migrations.AddField(
            model_name='genefinding',
            name='type',
            field=models.CharField(choices=[('V', 'Genetic variation'), ('A', 'Molecular abundance')], default=None, max_length=2, null=True),
        ),
        migrations.AddConstraint(
            model_name='genefinding',
            constraint=models.UniqueConstraint(fields=('study_cohort', 'hgnc_gene', 'type'), name='unique_study_gene_type'),
        ),
    ]
