# Generated by Django 5.2.3 on 2025-07-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0021_remove_genefinding_unique_study_gene_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genefinding',
            name='type',
            field=models.CharField(choices=[('V', 'Genetic variation'), ('A', 'Molecular abundance')], default=None, max_length=1, null=True),
        ),
    ]
