# Generated by Django 5.2.3 on 2025-07-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0023_genefinding_sickgenes_genefinding_type_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genefinding',
            name='study_cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_cohorts', to='sickgenes.studycohort'),
        ),
    ]
