# Generated by Django 5.2.3 on 2025-07-05 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0024_alter_genefinding_study_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genefinding',
            name='study_cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gene_findings', to='sickgenes.studycohort'),
        ),
    ]
