# Generated by Django 5.2.3 on 2025-07-06 14:08

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0025_alter_genefinding_study_cohort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hmdbmetabolite',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='bigg_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='biocyc_id',
            field=models.CharField(default=None, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='cas_registry_number',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='chebi_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='chemspider_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='drugbank_id',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='foodb_id',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='iupac_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='knapsack_id',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='pubchem_compound_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='secondary_accessions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='synonyms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='traditional_iupac',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='wikipedia_id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hmdbmetabolite',
            name='accession',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='hmdbmetabolite',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['accession'], name='hmdbmetabolite_accession_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['name'], name='hmdbmetabolite_name_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['cas_registry_number'], name='hmdbmetabolite_cas_num_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['drugbank_id'], name='hmdbmetabolite_drugbank_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['foodb_id'], name='hmdbmetabolite_foodb_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['knapsack_id'], name='hmdbmetabolite_knapsack_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['biocyc_id'], name='hmdbmetabolite_biocyc_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['wikipedia_id'], name='hmdbmetabolite_wiki_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['iupac_name'], name='hmdbmetabolite_iupac_name_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['traditional_iupac'], name='hmdbmetabolite_tradiupac_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['bigg_id'], name='hmdbmetabolite_bigg_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['pubchem_compound_id'], name='hmdbmetabolite_pubchem_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['chemspider_id'], name='hmdbmetabolite_chemspider_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['chebi_id'], name='hmdbmetabolite_chebi_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=django.contrib.postgres.indexes.GinIndex(fields=['secondary_accessions'], name='hmdbmetabolite_secondary_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=django.contrib.postgres.indexes.GinIndex(fields=['synonyms'], name='hmdbmetabolite_synonyms_idx'),
        ),
    ]
