# Generated by Django 5.2.3 on 2025-07-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0026_alter_hmdbmetabolite_options_hmdbmetabolite_bigg_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgncgene',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
