# Generated by Django 5.2.3 on 2025-07-07 14:42

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0029_remove_hmdbmetabolite_hmdbmetabolite_iupac_name_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_iupac_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_tradiupac_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_synonyms_idx',
        ),
        migrations.RenameField(
            model_name='hmdbmetabolite',
            old_name='searchable_iupac_name',
            new_name='iupac_name',
        ),
        migrations.RenameField(
            model_name='hmdbmetabolite',
            old_name='searchable_synonyms',
            new_name='synonyms',
        ),
        migrations.RenameField(
            model_name='hmdbmetabolite',
            old_name='searchable_traditional_iupac',
            new_name='traditional_iupac',
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['iupac_name'], name='hmdbmetabolite_iupac_name_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=models.Index(fields=['traditional_iupac'], name='hmdbmetabolite_tradiupac_idx'),
        ),
        migrations.AddIndex(
            model_name='hmdbmetabolite',
            index=django.contrib.postgres.indexes.GinIndex(fields=['synonyms'], name='hmdbmetabolite_synonyms_idx'),
        ),
    ]
