# Generated by Django 5.2.3 on 2025-07-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0030_remove_hmdbmetabolite_hmdbmetabolite_iupac_name_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hgncgene',
            name='datetime_updated',
        ),
    ]
