# Generated by Django 5.2.3 on 2025-07-07 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0031_remove_hgncgene_datetime_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaboliteFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('hmdb_metabolite', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sickgenes.hmdbmetabolite')),
                ('study_cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metabolite_findings', to='sickgenes.studycohort')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('study_cohort', 'hmdb_metabolite'), name='unique_study_cohort_metabolite_')],
            },
        ),
    ]
