# Generated by Django 5.2.3 on 2025-07-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0032_metabolitefinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='studycohort',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
