# Generated by Django 5.2.3 on 2025-07-08 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0033_studycohort_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AliasSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaboliteSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OmimId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrevName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrevSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondaryAccession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UniprotId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveIndex(
            model_name='hgncgene',
            name='hgncgene_symbol_idx',
        ),
        migrations.RemoveIndex(
            model_name='hgncgene',
            name='hgncgene_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='hgncgene',
            name='hgncgene_entrez_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hgncgene',
            name='hgncgene_vega_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hgncgene',
            name='hgncgene_ucsc_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hgncgene',
            name='hgncgene_ensembl_gene_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_accession_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_cas_num_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_drugbank_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_foodb_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_knapsack_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_biocyc_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_wiki_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_bigg_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_pubchem_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_chemspider_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_chebi_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_secondary_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_iupac_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_tradiupac_idx',
        ),
        migrations.RemoveIndex(
            model_name='hmdbmetabolite',
            name='hmdbmetabolite_synonyms_idx',
        ),
        migrations.RemoveField(
            model_name='hgncgene',
            name='alias_name',
        ),
        migrations.RemoveField(
            model_name='hgncgene',
            name='alias_symbol',
        ),
        migrations.RemoveField(
            model_name='hgncgene',
            name='ena',
        ),
        migrations.RemoveField(
            model_name='hgncgene',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hgncgene',
            name='omim_id',
        ),
        migrations.RemoveField(
            model_name='hgncgene',
            name='prev_name',
        ),
        migrations.RemoveField(
            model_name='hgncgene',
            name='prev_symbol',
        ),
        migrations.RemoveField(
            model_name='hgncgene',
            name='uniprot_ids',
        ),
        migrations.RemoveField(
            model_name='hmdbmetabolite',
            name='secondary_accessions',
        ),
        migrations.RemoveField(
            model_name='hmdbmetabolite',
            name='synonyms',
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='ensembl_gene_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='entrez_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='hgnc_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='symbol',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='ucsc_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='vega_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='hmdbmetabolite',
            name='iupac_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hmdbmetabolite',
            name='traditional_iupac',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aliasname',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene'),
        ),
        migrations.AddField(
            model_name='aliassymbol',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene'),
        ),
        migrations.AddField(
            model_name='ena',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene'),
        ),
        migrations.AddField(
            model_name='metabolitesynonym',
            name='metabolite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='sickgenes.hmdbmetabolite'),
        ),
        migrations.AddField(
            model_name='omimid',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene'),
        ),
        migrations.AddField(
            model_name='prevname',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene'),
        ),
        migrations.AddField(
            model_name='prevsymbol',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene'),
        ),
        migrations.AddField(
            model_name='secondaryaccession',
            name='metabolite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_accessions', to='sickgenes.hmdbmetabolite'),
        ),
        migrations.AddField(
            model_name='uniprotid',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene'),
        ),
        migrations.AlterUniqueTogether(
            name='aliasname',
            unique_together={('gene', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='aliassymbol',
            unique_together={('gene', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='ena',
            unique_together={('gene', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='metabolitesynonym',
            unique_together={('metabolite', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='omimid',
            unique_together={('gene', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='prevname',
            unique_together={('gene', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='prevsymbol',
            unique_together={('gene', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='secondaryaccession',
            unique_together={('metabolite', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='uniprotid',
            unique_together={('gene', 'value')},
        ),
    ]
