# Generated by Django 5.2.3 on 2025-07-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0034_aliasname_aliassymbol_ena_metabolitesynonym_omimid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hgncgene',
            name='hgnc_id',
        ),
        migrations.AddField(
            model_name='hgncgene',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
