# Generated by Django 5.2.3 on 2025-07-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0035_remove_hgncgene_hgnc_id_hgncgene_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgncgene',
            name='hgnc_id',
            field=models.CharField(default=None, max_length=15, null=True, unique=True),
        ),
    ]
