# Generated by Django 5.2.3 on 2025-07-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0036_hgncgene_hgnc_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aliassymbol',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='aliassymbol',
            name='gene',
        ),
        migrations.AlterUniqueTogether(
            name='ena',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ena',
            name='gene',
        ),
        migrations.AlterUniqueTogether(
            name='omimid',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='omimid',
            name='gene',
        ),
        migrations.AlterUniqueTogether(
            name='prevname',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prevname',
            name='gene',
        ),
        migrations.AlterUniqueTogether(
            name='prevsymbol',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prevsymbol',
            name='gene',
        ),
        migrations.AlterUniqueTogether(
            name='uniprotid',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='uniprotid',
            name='gene',
        ),
        migrations.DeleteModel(
            name='AliasName',
        ),
        migrations.DeleteModel(
            name='AliasSymbol',
        ),
        migrations.DeleteModel(
            name='Ena',
        ),
        migrations.DeleteModel(
            name='OmimId',
        ),
        migrations.DeleteModel(
            name='PrevName',
        ),
        migrations.DeleteModel(
            name='PrevSymbol',
        ),
        migrations.DeleteModel(
            name='UniprotId',
        ),
    ]
