# Generated by Django 5.2.3 on 2025-07-08 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0037_alter_aliassymbol_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene')),
            ],
            options={
                'abstract': False,
                'unique_together': {('gene', 'value')},
            },
        ),
        migrations.CreateModel(
            name='AliasSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene')),
            ],
            options={
                'abstract': False,
                'unique_together': {('gene', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Ena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene')),
            ],
            options={
                'abstract': False,
                'unique_together': {('gene', 'value')},
            },
        ),
        migrations.CreateModel(
            name='OmimId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene')),
            ],
            options={
                'abstract': False,
                'unique_together': {('gene', 'value')},
            },
        ),
        migrations.CreateModel(
            name='PrevName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene')),
            ],
            options={
                'abstract': False,
                'unique_together': {('gene', 'value')},
            },
        ),
        migrations.CreateModel(
            name='PrevSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=40)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene')),
            ],
            options={
                'abstract': False,
                'unique_together': {('gene', 'value')},
            },
        ),
        migrations.CreateModel(
            name='UniprotId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene')),
            ],
            options={
                'abstract': False,
                'unique_together': {('gene', 'value')},
            },
        ),
    ]
