# Generated by Django 5.2.3 on 2025-07-08 18:37

import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0038_aliasname_aliassymbol_ena_omimid_prevname_prevsymbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgncgene',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='hmdbmetabolite',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='metabolitesynonym',
            name='metabolite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hmdbmetabolite'),
        ),
        migrations.AlterField(
            model_name='secondaryaccession',
            name='metabolite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hmdbmetabolite'),
        ),
    ]
