# Generated by Django 5.2.3 on 2025-07-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0040_remove_hgncgene_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='authors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='doi',
            field=models.CharField(max_length=255, unique=True, verbose_name='DOI URL'),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
