# Generated by Django 5.2.3 on 2025-07-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0041_study_authors_study_publication_date_alter_study_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
