# Generated by Django 5.2.3 on 2025-07-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0042_alter_study_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
