# Generated by Django 5.2.3 on 2025-07-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0043_alter_study_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='study',
            name='publication_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Day'),
        ),
        migrations.AddField(
            model_name='study',
            name='publication_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='study',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year'),
        ),
    ]
