# Generated by Django 5.2.3 on 2025-07-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0044_remove_study_publication_date_study_publication_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='DOI URL'),
        ),
        migrations.AlterField(
            model_name='study',
            name='publication_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Publication Day'),
        ),
        migrations.AlterField(
            model_name='study',
            name='publication_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Publication Month'),
        ),
        migrations.AlterField(
            model_name='study',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Publication Year'),
        ),
    ]
