# Generated by Django 5.2.4 on 2025-07-11 20:35

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0045_alter_study_doi_alter_study_publication_day_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aliasname',
            index=models.Index(django.db.models.functions.text.Upper('value'), name='aliasname_value_idx'),
        ),
        migrations.AddIndex(
            model_name='aliassymbol',
            index=models.Index(django.db.models.functions.text.Upper('value'), name='aliassymbol_value_idx'),
        ),
        migrations.AddIndex(
            model_name='ena',
            index=models.Index(django.db.models.functions.text.Upper('value'), name='ena_value_idx'),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(django.db.models.functions.text.Upper('hgnc_id'), name='hgncgene_hgncid_iexact_idx'),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(django.db.models.functions.text.Upper('symbol'), name='hgncgene_symbol_iexact_idx'),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(django.db.models.functions.text.Upper('name'), name='hgncgene_name_iexact_idx'),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(django.db.models.functions.text.Upper('entrez_id'), name='hgncgene_entrez_id_iexact_idx'),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(django.db.models.functions.text.Upper('ensembl_gene_id'), name='hgncgene_ensembl_iexact_idx'),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(django.db.models.functions.text.Upper('vega_id'), name='hgncgene_vega_id_iexact_idx'),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(django.db.models.functions.text.Upper('ucsc_id'), name='hgncgene_ucsc_id_iexact_idx'),
        ),
        migrations.AddIndex(
            model_name='prevname',
            index=models.Index(django.db.models.functions.text.Upper('value'), name='prevname_value_idx'),
        ),
        migrations.AddIndex(
            model_name='prevsymbol',
            index=models.Index(django.db.models.functions.text.Upper('value'), name='prevsymbol_value_idx'),
        ),
        migrations.AddIndex(
            model_name='uniprotid',
            index=models.Index(django.db.models.functions.text.Upper('value'), name='uniprotid_value_idx'),
        ),
    ]
