# Generated by Django 5.2.4 on 2025-07-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0046_aliasname_aliasname_value_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='not_finished',
            field=models.BooleanField(default=False),
        ),
    ]
