# Generated by Django 5.2.4 on 2025-07-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0047_study_not_finished'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='genefinding',
            name='unique_study_gene_type',
        ),
        migrations.RemoveConstraint(
            model_name='genefinding',
            name='sickgenes_genefinding_type_valid',
        ),
        migrations.RemoveField(
            model_name='genefinding',
            name='type',
        ),
    ]
