# Generated by Django 5.2.4 on 2025-07-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0048_remove_genefinding_unique_study_gene_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='genefinding',
            constraint=models.UniqueConstraint(fields=('study_cohort', 'hgnc_gene'), name='unique_study_gene'),
        ),
    ]
