# Generated by Django 5.2.4 on 2025-07-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0051_alter_studycohort_disease_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringProtein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=16, unique=True)),
                ('hgnc_id', models.CharField(max_length=11)),
                ('hgnc_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sickgenes.hgncgene')),
            ],
        ),
    ]
