# Generated by Django 5.2.4 on 2025-07-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0052_stringprotein'),
    ]

    operations = [
        migrations.CreateModel(
            name='StringInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_score', models.SmallIntegerField()),
                ('protein1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein1_interactions', to='sickgenes.stringprotein')),
                ('protein2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein2_interactions', to='sickgenes.stringprotein')),
            ],
        ),
    ]
