# Generated by Django 5.2.4 on 2025-07-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0053_stringinteraction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stringinteraction',
            index=models.Index(fields=['protein1'], name='stringinteraction_protein1_idx'),
        ),
        migrations.AddIndex(
            model_name='stringinteraction',
            index=models.Index(fields=['protein2'], name='stringinteraction_protein2_idx'),
        ),
    ]
