# Generated by Django 5.2.4 on 2025-07-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0054_stringinteraction_stringinteraction_protein1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
    ]
