# Generated by Django 5.2.4 on 2025-07-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0055_study_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study',
            old_name='publisher',
            new_name='journal_titles',
        ),
    ]
