# Generated by Django 5.2.4 on 2025-07-16 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0056_rename_publisher_study_journal_titles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stringinteraction',
            unique_together={('protein1', 'protein2')},
        ),
    ]
