# Generated by Django 5.2.4 on 2025-07-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0057_alter_stringinteraction_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
