# Generated by Django 5.2.4 on 2025-07-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0058_study_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
