# Generated by Django 5.2.4 on 2025-12-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0059_siteconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='criteria',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='Site Name', max_length=255),
        ),
    ]
