# Generated by Django 5.2.4 on 2025-12-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0060_remove_siteconfiguration_criteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
