# Generated by Django 5.2.4 on 2025-12-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0061_siteconfiguration_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='pmid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
