# Generated by Django 5.2.4 on 2025-12-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0062_study_pmid'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='pmid',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='PubMed ID'),
        ),
    ]
