# Generated by Django 5.2.4 on 2025-12-30 03:17

from django.db import migrations
from django.utils.text import slugify

def create_slugs(apps, schema_editor):
    Study = apps.get_model("sickgenes", "Study")

    for study in Study.objects.all():
        study.slug = slugify(f'{study.title}-{study.publication_year}')
        study.save()

def reverse_slugs(apps, schema_editor):
    Study = apps.get_model('sickgenes', 'Study')
    Study.objects.all().update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0063_study_slug_alter_study_pmid'),
    ]

    operations = [
        migrations.RunPython(create_slugs, reverse_slugs),
    ]
