# Generated by Django 5.2.4 on 2026-01-02 15:32

from django.db import migrations
from django.utils.text import slugify

def update_slugs_to_short_length(apps, schema_editor):
    Study = apps.get_model("sickgenes", "Study")

    for study in Study.objects.all():
        study.slug = slugify(f'{study.title[:80]}-{study.publication_year}')
        study.save()

def reverse_update_slugs(apps, schema_editor):
    Study = apps.get_model('sickgenes', 'Study')
    for study in Study.objects.all():
        study.slug = slugify(f'{study.title}-{study.publication_year}')
        study.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0064_auto_20251230_0317'),
    ]

    operations = [
        migrations.RunPython(update_slugs_to_short_length, reverse_update_slugs),
    ]
