# Generated by Django 5.2.4 on 2026-01-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0065_auto_20260102_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='home_page_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
