# Generated by Django 5.2.4 on 2026-01-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0066_siteconfiguration_home_page_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hgncgene',
            name='hgnc_id_int',
            field=models.IntegerField(null=True),
        ),
    ]
