# Generated by Django 5.2.4 on 2026-01-24 01:28

from django.db import migrations

def extract_hgnc_numbers(apps, schema_editor):
    HgncGene = apps.get_model('sickgenes', 'HgncGene')
    genes_to_update = []

    for gene in HgncGene.objects.all():
        if gene.hgnc_id:
            try:
                gene.hgnc_id_int = int(gene.hgnc_id.split(':')[1])
                genes_to_update.append(gene)
            except (IndexError, ValueError):
                print(f"Warning: Could not parse hgnc_id: {gene.hgnc_id}")
        
    HgncGene.objects.bulk_update(genes_to_update, ['hgnc_id_int'], batch_size=1000)

def reverse_migration(apps, schema_editor):
    HgncGene = apps.get_model('yourapp', 'HgncGene')
    HgncGene.objects.update(hgnc_id_int=None)

class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0067_auto_20260124_0124'),
    ]

    operations = [
        migrations.RunPython(extract_hgnc_numbers, reverse_migration),
    ]
