# Generated by Django 5.2.4 on 2026-01-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0068_auto_20260124_0128'),
    ]

    operations = [
        # Remove old indexes first
        migrations.RemoveIndex(
            model_name='hgncgene',
            name='hgncgene_hgncid_iexact_idx',
        ),
        # Remove old field
        migrations.RemoveField(
            model_name='hgncgene',
            name='hgnc_id',
        ),
        # Rename new field
        migrations.RenameField(
            model_name='hgncgene',
            old_name='hgnc_id_int',
            new_name='hgnc_id',
        ),
        # Add unique constraint
        migrations.AlterField(
            model_name='hgncgene',
            name='hgnc_id',
            field=models.IntegerField(unique=True, null=True, default=None),
        ),
    ]
