# Generated by Django 5.2.4 on 2026-01-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0069_auto_20260124_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='code',
            field=models.CharField(default=None, max_length=100, null=True, unique=True),
        ),
    ]
