# Generated by Django 5.2.4 on 2026-01-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0070_disease_code'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hgncgene',
            name='hgncgene_entrez_id_iexact_idx',
        ),
        migrations.AlterField(
            model_name='hgncgene',
            name='entrez_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='hgncgene',
            index=models.Index(models.F('entrez_id'), name='hgncgene_entrez_id_idx'),
        ),
    ]
