# Generated by Django 5.2.4 on 2026-04-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickgenes', '0071_remove_hgncgene_hgncgene_entrez_id_iexact_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='newest_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_versions', to='sickgenes.study'),
        ),
    ]
